/*Criando o banco*/
CREATE DATABASE optus;
GO

/*TABELA*/
CREATE TABLE usuario(
	idUsuario INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR (100) NOT NULL,
	endereco VARCHAR (20),
	email VARCHAR (100),
	senha VARCHAR (20),
	tipoAcesso VARCHAR (20)
);

CREATE TABLE artista(
	idArtista INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR (100) NOT NULL,

	
);

CREATE TABLE cds(
	idcds INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR (100) NOT NULL,
	idArtista INT FOREIGN KEY REFERENCES artista (idArtista),

	
);
CREATE TABLE albuns(
	IdAlbuns INT PRIMARY KEY IDENTITY NOT NULL,
	--CHAMANDO CHAVES ESTRANGEIRAS
	idArtista INT FOREIGN KEY REFERENCES artista (idArtista),
	idcds INT FOREIGN KEY REFERENCES cds (idcds),

);

CREATE TABLE empresa(
	IdEmpresa INT PRIMARY KEY IDENTITY NOT NULL,
	--CHAMANDO CHAVES ESTRANGEIRAS
	idUsuario INT FOREIGN KEY REFERENCES usuario (idUsuario),
	tipoAcesso VARCHAR (20),
	idArtista INT FOREIGN KEY REFERENCES artista (idArtista),

);


